name: frontend

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: frontend

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: aws s3 sync . s3://udemy-github-actions-nagisano33 --exact-timestamps --region ap-northeast-1
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.FRONTEND_AWS_ACESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.FRONTEND_AWS_SECRET_ACCESS_KEY}}